# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Lida Shahmiri 
description: "I am a Doctoral researcher in computer science, specialised in statistical modelling, with expertise in analysing large datasets using Python and ML to draw inferences. My specific interest is in developing scalable ML pipelines and promoting interdisciplinary research that combines AI theory and practice with domain expertise. I have worked with interdisciplinary teams and have strong communication skills, having delivered numerous research and outreach talks to diverse audiences. Please visit my Github & LinkedIn pages (or download my Resume) by using the links below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "Milton Keynes, UK"
resume_url: /docs/Lida_Shahmiri_CV.pdf 
avatar_image: /img/LidaShahmiri.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/lida-shahmiri/" # Add your linkedln handle
github: "https://github.com/LShahmiri/"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

